/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) racecar_lap_time_mpc_impl_dae_fun_jac_x_xdot_u_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {7, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {1, 1, 1};
static const casadi_int casadi_s4[32] = 
  {7, 7, 0, 0, 7, 13, 17, 19,
  22, 22, 0, 1, 2, 3, 4, 5,
  6, 0, 1, 2, 3, 4, 5, 1,
  2, 3, 5, 0, 5, 0, 4, 5};
static const casadi_int casadi_s5[10] = 
  {7, 7, 0, 0, 0, 0, 0, 0,
  0, 0};
static const casadi_int casadi_s6[9] = 
  {7, 2, 0, 3, 4, 1, 2, 3,
  1};

/* racecar_lap_time_mpc_impl_dae_fun_jac_x_xdot_u:(i0[7],i1[7],i2[2],i3[],i4)->(o0[7],o1[7x7,22nz],o2[7x7,0nz],o3[7x2,4nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28;
  a00=arg[0]? arg[0][1] : 0;
  a01=arg[0]? arg[0][5] : 0;
  a02=cos(a01);
  a03=(a00*a02);
  a04=arg[0]? arg[0][2] : 0;
  a01=sin(a01);
  a05=(a04*a01);
  a03=(a03-a05);
  a05=1.;
  a06=arg[0]? arg[0][4] : 0;
  a07=arg[4]? arg[4][0] : 0;
  a06=(a06*a07);
  a06=(a05-a06);
  a08=(a03/a06);
  if (res[0]!=0) res[0][0]=a08;
  a09=arg[2]? arg[2][1] : 0;
  a10=68.;
  a11=arg[2]? arg[2][0] : 0;
  a12=1.0000000000000000e-03;
  a12=(a00+a12);
  a13=(a04/a12);
  a14=(a11-a13);
  a15=1.2500000000000000e-01;
  a16=arg[0]? arg[0][3] : 0;
  a17=(a15*a16);
  a17=(a17/a12);
  a14=(a14+a17);
  a14=(a10*a14);
  a18=sin(a11);
  a19=(a14*a18);
  a20=1.8000000000000000e+00;
  a21=(a19/a20);
  a09=(a09-a21);
  a21=7.8480000000000008e+00;
  a09=(a09-a21);
  a21=(a16*a04);
  a09=(a09+a21);
  if (res[0]!=0) res[0][1]=a09;
  a11=cos(a11);
  a09=(a14*a11);
  a21=(a09/a20);
  a22=71.;
  a23=(a13+a17);
  a23=(a22*a23);
  a20=(a23/a20);
  a21=(a21-a20);
  a20=(a16*a00);
  a21=(a21-a20);
  if (res[0]!=0) res[0][2]=a21;
  a14=(a15*a14);
  a21=(a14*a11);
  a23=(a15*a23);
  a21=(a21+a23);
  a23=2.9999999999999999e-02;
  a21=(a21/a23);
  if (res[0]!=0) res[0][3]=a21;
  a21=(a00*a01);
  a23=(a04*a02);
  a21=(a21+a23);
  if (res[0]!=0) res[0][4]=a21;
  a23=(a03*a07);
  a23=(a23/a06);
  a20=(a16-a23);
  if (res[0]!=0) res[0][5]=a20;
  a20=-3.3333333333333332e-04;
  a24=1.0718750000000001e-02;
  a25=casadi_sq(a00);
  a25=(a24*a25);
  a26=1.4126400000000002e+01;
  a27=(a26*a00);
  a25=(a25+a27);
  a25=(a20*a25);
  if (res[0]!=0) res[0][6]=a25;
  a25=(a02/a06);
  if (res[1]!=0) res[1][0]=a25;
  a25=5.5555555555555558e-01;
  a13=(a13/a12);
  a17=(a17/a12);
  a27=(a13-a17);
  a27=(a10*a27);
  a28=(a18*a27);
  a28=(a25*a28);
  a28=(-a28);
  if (res[1]!=0) res[1][1]=a28;
  a28=(a11*a27);
  a28=(a25*a28);
  a13=(a13+a17);
  a13=(a22*a13);
  a17=(a25*a13);
  a28=(a28+a17);
  a28=(a28-a16);
  if (res[1]!=0) res[1][2]=a28;
  a28=3.3333333333333336e+01;
  a27=(a15*a27);
  a27=(a11*a27);
  a13=(a15*a13);
  a27=(a27-a13);
  a27=(a28*a27);
  if (res[1]!=0) res[1][3]=a27;
  if (res[1]!=0) res[1][4]=a01;
  a27=(a07*a02);
  a27=(a27/a06);
  a27=(-a27);
  if (res[1]!=0) res[1][5]=a27;
  a27=(a00+a00);
  a24=(a24*a27);
  a24=(a24+a26);
  a20=(a20*a24);
  if (res[1]!=0) res[1][6]=a20;
  a20=(a01/a06);
  a20=(-a20);
  if (res[1]!=0) res[1][7]=a20;
  a20=(a10/a12);
  a24=(a18*a20);
  a24=(a25*a24);
  a24=(a24+a16);
  if (res[1]!=0) res[1][8]=a24;
  a24=(a11*a20);
  a24=(a25*a24);
  a16=(a22/a12);
  a26=(a25*a16);
  a24=(a24+a26);
  a24=(-a24);
  if (res[1]!=0) res[1][9]=a24;
  a16=(a15*a16);
  a20=(a15*a20);
  a20=(a11*a20);
  a16=(a16-a20);
  a16=(a28*a16);
  if (res[1]!=0) res[1][10]=a16;
  if (res[1]!=0) res[1][11]=a02;
  a01=(a07*a01);
  a01=(a01/a06);
  if (res[1]!=0) res[1][12]=a01;
  a12=(a15/a12);
  a01=(a10*a12);
  a02=(a18*a01);
  a02=(a25*a02);
  a04=(a04-a02);
  if (res[1]!=0) res[1][13]=a04;
  a04=(a11*a01);
  a04=(a25*a04);
  a22=(a22*a12);
  a12=(a25*a22);
  a04=(a04-a12);
  a04=(a04-a00);
  if (res[1]!=0) res[1][14]=a04;
  a01=(a15*a01);
  a01=(a11*a01);
  a15=(a15*a22);
  a01=(a01+a15);
  a01=(a28*a01);
  if (res[1]!=0) res[1][15]=a01;
  if (res[1]!=0) res[1][16]=a05;
  a08=(a08/a06);
  a08=(a08*a07);
  if (res[1]!=0) res[1][17]=a08;
  a23=(a23/a06);
  a23=(a23*a07);
  a23=(-a23);
  if (res[1]!=0) res[1][18]=a23;
  a23=(a21/a06);
  a23=(-a23);
  if (res[1]!=0) res[1][19]=a23;
  if (res[1]!=0) res[1][20]=a03;
  a07=(a07*a21);
  a07=(a07/a06);
  if (res[1]!=0) res[1][21]=a07;
  a07=(a10*a18);
  a07=(a07+a09);
  a07=(a25*a07);
  a07=(-a07);
  if (res[3]!=0) res[3][0]=a07;
  a10=(a10*a11);
  a10=(a10-a19);
  a25=(a25*a10);
  if (res[3]!=0) res[3][1]=a25;
  a25=8.5000000000000000e+00;
  a25=(a25*a11);
  a14=(a14*a18);
  a25=(a25-a14);
  a28=(a28*a25);
  if (res[3]!=0) res[3][2]=a28;
  if (res[3]!=0) res[3][3]=a05;
  return 0;
}

CASADI_SYMBOL_EXPORT int racecar_lap_time_mpc_impl_dae_fun_jac_x_xdot_u(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int racecar_lap_time_mpc_impl_dae_fun_jac_x_xdot_u_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int racecar_lap_time_mpc_impl_dae_fun_jac_x_xdot_u_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void racecar_lap_time_mpc_impl_dae_fun_jac_x_xdot_u_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int racecar_lap_time_mpc_impl_dae_fun_jac_x_xdot_u_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void racecar_lap_time_mpc_impl_dae_fun_jac_x_xdot_u_release(int mem) {
}

CASADI_SYMBOL_EXPORT void racecar_lap_time_mpc_impl_dae_fun_jac_x_xdot_u_incref(void) {
}

CASADI_SYMBOL_EXPORT void racecar_lap_time_mpc_impl_dae_fun_jac_x_xdot_u_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int racecar_lap_time_mpc_impl_dae_fun_jac_x_xdot_u_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int racecar_lap_time_mpc_impl_dae_fun_jac_x_xdot_u_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real racecar_lap_time_mpc_impl_dae_fun_jac_x_xdot_u_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* racecar_lap_time_mpc_impl_dae_fun_jac_x_xdot_u_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* racecar_lap_time_mpc_impl_dae_fun_jac_x_xdot_u_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* racecar_lap_time_mpc_impl_dae_fun_jac_x_xdot_u_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* racecar_lap_time_mpc_impl_dae_fun_jac_x_xdot_u_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int racecar_lap_time_mpc_impl_dae_fun_jac_x_xdot_u_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int racecar_lap_time_mpc_impl_dae_fun_jac_x_xdot_u_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
