/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) racecar_lap_time_mpc_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {7, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};
static const casadi_int casadi_s3[3] = {9, 1, 1};

/* racecar_lap_time_mpc_expl_vde_adj:(i0[7],i1[7],i2[2],i3)->(o0[9]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  a01=2.1189600000000002e+01;
  a02=-3.3333333333333332e-04;
  a03=arg[1]? arg[1][6] : 0;
  a02=(a02*a03);
  a01=(a01*a02);
  a03=arg[0]? arg[0][1] : 0;
  a04=(a03+a03);
  a05=1.0718750000000001e-02;
  a05=(a05*a02);
  a04=(a04*a05);
  a01=(a01+a04);
  a04=arg[0]? arg[0][5] : 0;
  a05=cos(a04);
  a02=arg[3]? arg[3][0] : 0;
  a06=arg[1]? arg[1][5] : 0;
  a07=1.;
  a08=arg[0]? arg[0][4] : 0;
  a08=(a08*a02);
  a07=(a07-a08);
  a08=(a06/a07);
  a08=(a02*a08);
  a09=(a05*a08);
  a01=(a01-a09);
  a04=sin(a04);
  a09=arg[1]? arg[1][4] : 0;
  a10=(a04*a09);
  a01=(a01+a10);
  a10=arg[0]? arg[0][3] : 0;
  a11=arg[1]? arg[1][2] : 0;
  a12=(a10*a11);
  a01=(a01-a12);
  a12=arg[0]? arg[0][2] : 0;
  a13=1.0000000000000000e-03;
  a13=(a03+a13);
  a14=(a12/a13);
  a15=(a14/a13);
  a16=68.;
  a17=1.2500000000000000e-01;
  a18=arg[2]? arg[2][0] : 0;
  a19=cos(a18);
  a20=3.3333333333333336e+01;
  a21=arg[1]? arg[1][3] : 0;
  a20=(a20*a21);
  a21=(a19*a20);
  a21=(a17*a21);
  a22=5.5555555555555558e-01;
  a23=(a22*a11);
  a24=(a19*a23);
  a21=(a21+a24);
  a24=sin(a18);
  a25=arg[1]? arg[1][1] : 0;
  a22=(a22*a25);
  a26=(a24*a22);
  a21=(a21-a26);
  a21=(a16*a21);
  a26=(a15*a21);
  a27=(a17*a10);
  a27=(a27/a13);
  a28=(a27/a13);
  a29=71.;
  a30=(a17*a20);
  a30=(a30-a23);
  a29=(a29*a30);
  a30=(a28*a29);
  a15=(a15*a29);
  a30=(a30+a15);
  a28=(a28*a21);
  a30=(a30+a28);
  a26=(a26-a30);
  a01=(a01+a26);
  a26=arg[1]? arg[1][0] : 0;
  a30=(a26/a07);
  a28=(a05*a30);
  a01=(a01+a28);
  if (res[0]!=0) res[0][1]=a01;
  a01=(a04*a08);
  a28=(a05*a09);
  a01=(a01+a28);
  a29=(a29/a13);
  a01=(a01+a29);
  a10=(a10*a25);
  a01=(a01+a10);
  a13=(a21/a13);
  a01=(a01-a13);
  a10=(a04*a30);
  a01=(a01-a10);
  if (res[0]!=0) res[0][2]=a01;
  a11=(a03*a11);
  a11=(a06-a11);
  a29=(a17*a29);
  a11=(a11+a29);
  a29=(a12*a25);
  a11=(a11+a29);
  a13=(a17*a13);
  a11=(a11+a13);
  if (res[0]!=0) res[0][3]=a11;
  a11=(a03*a05);
  a13=(a12*a04);
  a11=(a11-a13);
  a13=(a11/a07);
  a13=(a13/a07);
  a13=(a13*a26);
  a13=(a02*a13);
  a11=(a11*a02);
  a11=(a11/a07);
  a11=(a11/a07);
  a11=(a11*a06);
  a02=(a02*a11);
  a13=(a13-a02);
  if (res[0]!=0) res[0][4]=a13;
  a13=(a12*a08);
  a13=(a05*a13);
  a08=(a03*a08);
  a08=(a04*a08);
  a13=(a13+a08);
  a08=(a12*a09);
  a08=(a04*a08);
  a13=(a13-a08);
  a09=(a03*a09);
  a09=(a05*a09);
  a13=(a13+a09);
  a12=(a12*a30);
  a05=(a05*a12);
  a13=(a13-a05);
  a03=(a03*a30);
  a04=(a04*a03);
  a13=(a13-a04);
  if (res[0]!=0) res[0][5]=a13;
  if (res[0]!=0) res[0][6]=a00;
  a18=(a18-a14);
  a18=(a18+a27);
  a16=(a16*a18);
  a17=(a17*a16);
  a17=(a17*a20);
  a17=(a24*a17);
  a23=(a16*a23);
  a24=(a24*a23);
  a17=(a17+a24);
  a16=(a16*a22);
  a19=(a19*a16);
  a17=(a17+a19);
  a21=(a21-a17);
  if (res[0]!=0) res[0][7]=a21;
  if (res[0]!=0) res[0][8]=a25;
  return 0;
}

CASADI_SYMBOL_EXPORT int racecar_lap_time_mpc_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int racecar_lap_time_mpc_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int racecar_lap_time_mpc_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void racecar_lap_time_mpc_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int racecar_lap_time_mpc_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void racecar_lap_time_mpc_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void racecar_lap_time_mpc_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void racecar_lap_time_mpc_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int racecar_lap_time_mpc_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int racecar_lap_time_mpc_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real racecar_lap_time_mpc_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* racecar_lap_time_mpc_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* racecar_lap_time_mpc_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* racecar_lap_time_mpc_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* racecar_lap_time_mpc_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int racecar_lap_time_mpc_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int racecar_lap_time_mpc_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
