/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) racecar_lap_time_mpc_impl_dae_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {7, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {1, 1, 1};
static const casadi_int casadi_s4[45] = 
  {16, 16, 0, 0, 6, 11, 14, 18,
  22, 22, 22, 22, 22, 22, 22, 22,
  22, 26, 26, 1, 2, 3, 4, 5,
  14, 1, 3, 4, 5, 14, 1, 2,
  14, 1, 2, 4, 5, 1, 2, 4,
  5, 1, 2, 3, 14};

/* racecar_lap_time_mpc_impl_dae_hess:(i0[7],i1[7],i2[2],i3[],i4[7],i5)->(o0[16x16,26nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31;
  a00=2.;
  a01=1.0718750000000001e-02;
  a02=-3.3333333333333332e-04;
  a03=arg[4]? arg[4][6] : 0;
  a02=(a02*a03);
  a01=(a01*a02);
  a00=(a00*a01);
  a01=71.;
  a02=1.2500000000000000e-01;
  a03=3.3333333333333336e+01;
  a04=arg[4]? arg[4][3] : 0;
  a03=(a03*a04);
  a04=(a02*a03);
  a05=5.5555555555555558e-01;
  a06=arg[4]? arg[4][2] : 0;
  a07=(a05*a06);
  a04=(a04-a07);
  a01=(a01*a04);
  a04=arg[0]? arg[0][3] : 0;
  a04=(a02*a04);
  a08=arg[0]? arg[0][1] : 0;
  a09=1.0000000000000000e-03;
  a09=(a08+a09);
  a04=(a04/a09);
  a10=(a04/a09);
  a11=(a10/a09);
  a11=(a11+a11);
  a12=(a01*a11);
  a13=arg[0]? arg[0][2] : 0;
  a14=(a13/a09);
  a15=(a14/a09);
  a16=(a15/a09);
  a16=(a16+a16);
  a17=(a01*a16);
  a12=(a12+a17);
  a17=68.;
  a18=arg[2]? arg[2][0] : 0;
  a19=cos(a18);
  a20=(a19*a03);
  a20=(a02*a20);
  a21=(a19*a07);
  a20=(a20+a21);
  a21=sin(a18);
  a22=arg[4]? arg[4][1] : 0;
  a05=(a05*a22);
  a23=(a21*a05);
  a20=(a20-a23);
  a20=(a17*a20);
  a11=(a20*a11);
  a12=(a12+a11);
  a16=(a20*a16);
  a12=(a12-a16);
  a00=(a00+a12);
  if (res[0]!=0) res[0][0]=a00;
  a00=(1./a09);
  a00=casadi_sq(a00);
  a12=(a20*a00);
  a00=(a01*a00);
  a12=(a12-a00);
  if (res[0]!=0) res[0][1]=a12;
  a01=(a01/a09);
  a01=(a01/a09);
  a01=(a02*a01);
  a06=(a06+a01);
  a20=(a20/a09);
  a20=(a20/a09);
  a20=(a02*a20);
  a06=(a06+a20);
  a06=(-a06);
  if (res[0]!=0) res[0][2]=a06;
  a20=arg[5]? arg[5][0] : 0;
  a01=arg[4]? arg[4][0] : 0;
  a00=arg[0]? arg[0][5] : 0;
  a16=cos(a00);
  a11=1.;
  a23=arg[0]? arg[0][4] : 0;
  a23=(a23*a20);
  a11=(a11-a23);
  a23=(a16/a11);
  a23=(a23/a11);
  a23=(a01*a23);
  a23=(a20*a23);
  a24=arg[4]? arg[4][5] : 0;
  a25=(a20*a16);
  a25=(a25/a11);
  a25=(a25/a11);
  a25=(a24*a25);
  a25=(a20*a25);
  a23=(a23-a25);
  if (res[0]!=0) res[0][3]=a23;
  a00=sin(a00);
  a25=(a24/a11);
  a25=(a20*a25);
  a26=(a00*a25);
  a27=arg[4]? arg[4][4] : 0;
  a28=(a16*a27);
  a26=(a26+a28);
  a28=(a01/a11);
  a29=(a00*a28);
  a26=(a26-a29);
  if (res[0]!=0) res[0][4]=a26;
  a15=(a15-a10);
  a15=(a17*a15);
  a10=(a02*a15);
  a10=(a03*a10);
  a10=(a21*a10);
  a29=(a07*a15);
  a29=(a21*a29);
  a10=(a10+a29);
  a15=(a05*a15);
  a15=(a19*a15);
  a10=(a10+a15);
  a10=(-a10);
  if (res[0]!=0) res[0][5]=a10;
  if (res[0]!=0) res[0][6]=a12;
  if (res[0]!=0) res[0][7]=a22;
  a12=(a20*a00);
  a12=(a12/a11);
  a12=(a12/a11);
  a12=(a24*a12);
  a12=(a20*a12);
  a15=(a00/a11);
  a15=(a15/a11);
  a15=(a01*a15);
  a15=(a20*a15);
  a12=(a12-a15);
  if (res[0]!=0) res[0][8]=a12;
  a15=(a16*a25);
  a29=(a00*a27);
  a15=(a15-a29);
  a29=(a16*a28);
  a15=(a15-a29);
  if (res[0]!=0) res[0][9]=a15;
  a29=(a17/a09);
  a30=(a02*a29);
  a30=(a03*a30);
  a30=(a21*a30);
  a31=(a07*a29);
  a31=(a21*a31);
  a30=(a30+a31);
  a29=(a05*a29);
  a29=(a19*a29);
  a30=(a30+a29);
  if (res[0]!=0) res[0][10]=a30;
  if (res[0]!=0) res[0][11]=a06;
  if (res[0]!=0) res[0][12]=a22;
  a09=(a02/a09);
  a09=(a17*a09);
  a22=(a02*a09);
  a22=(a03*a22);
  a22=(a21*a22);
  a06=(a07*a09);
  a06=(a21*a06);
  a22=(a22+a06);
  a09=(a05*a09);
  a09=(a19*a09);
  a22=(a22+a09);
  a22=(-a22);
  if (res[0]!=0) res[0][13]=a22;
  if (res[0]!=0) res[0][14]=a23;
  if (res[0]!=0) res[0][15]=a12;
  a12=(a08*a16);
  a23=(a13*a00);
  a12=(a12-a23);
  a23=(a12/a11);
  a23=(a23/a11);
  a09=(a23*a20);
  a09=(a09/a11);
  a23=(a23/a11);
  a23=(a23*a20);
  a09=(a09+a23);
  a09=(a01*a09);
  a09=(a20*a09);
  a12=(a12*a20);
  a12=(a12/a11);
  a12=(a12/a11);
  a23=(a12*a20);
  a23=(a23/a11);
  a12=(a12/a11);
  a12=(a12*a20);
  a23=(a23+a12);
  a23=(a24*a23);
  a23=(a20*a23);
  a09=(a09-a23);
  if (res[0]!=0) res[0][16]=a09;
  a09=(a08*a00);
  a23=(a13*a16);
  a09=(a09+a23);
  a23=(a20*a09);
  a23=(a23/a11);
  a23=(a23/a11);
  a24=(a24*a23);
  a24=(a20*a24);
  a09=(a09/a11);
  a09=(a09/a11);
  a01=(a01*a09);
  a20=(a20*a01);
  a24=(a24-a20);
  if (res[0]!=0) res[0][17]=a24;
  if (res[0]!=0) res[0][18]=a26;
  if (res[0]!=0) res[0][19]=a15;
  if (res[0]!=0) res[0][20]=a24;
  a24=(a08*a25);
  a24=(a24*a16);
  a25=(a13*a25);
  a25=(a25*a00);
  a24=(a24-a25);
  a25=(a13*a27);
  a25=(a25*a16);
  a24=(a24-a25);
  a27=(a08*a27);
  a27=(a27*a00);
  a24=(a24-a27);
  a13=(a13*a28);
  a13=(a13*a00);
  a24=(a24+a13);
  a08=(a08*a28);
  a08=(a08*a16);
  a24=(a24-a08);
  if (res[0]!=0) res[0][21]=a24;
  if (res[0]!=0) res[0][22]=a10;
  if (res[0]!=0) res[0][23]=a30;
  if (res[0]!=0) res[0][24]=a22;
  a22=(a03*a21);
  a22=(a02*a22);
  a30=(a07*a21);
  a22=(a22+a30);
  a30=(a05*a19);
  a22=(a22+a30);
  a22=(a17*a22);
  a18=(a18-a14);
  a18=(a18+a04);
  a18=(a17*a18);
  a02=(a02*a18);
  a02=(a02*a03);
  a02=(a02*a19);
  a04=8.5000000000000000e+00;
  a04=(a04*a03);
  a04=(a21*a04);
  a02=(a02+a04);
  a04=(a18*a07);
  a04=(a04*a19);
  a07=(a17*a07);
  a07=(a21*a07);
  a04=(a04+a07);
  a02=(a02+a04);
  a17=(a17*a05);
  a19=(a19*a17);
  a18=(a18*a05);
  a18=(a18*a21);
  a19=(a19-a18);
  a02=(a02+a19);
  a22=(a22+a02);
  a22=(-a22);
  if (res[0]!=0) res[0][25]=a22;
  return 0;
}

CASADI_SYMBOL_EXPORT int racecar_lap_time_mpc_impl_dae_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int racecar_lap_time_mpc_impl_dae_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int racecar_lap_time_mpc_impl_dae_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void racecar_lap_time_mpc_impl_dae_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int racecar_lap_time_mpc_impl_dae_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void racecar_lap_time_mpc_impl_dae_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void racecar_lap_time_mpc_impl_dae_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void racecar_lap_time_mpc_impl_dae_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int racecar_lap_time_mpc_impl_dae_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int racecar_lap_time_mpc_impl_dae_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real racecar_lap_time_mpc_impl_dae_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* racecar_lap_time_mpc_impl_dae_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* racecar_lap_time_mpc_impl_dae_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* racecar_lap_time_mpc_impl_dae_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s0;
    case 5: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* racecar_lap_time_mpc_impl_dae_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int racecar_lap_time_mpc_impl_dae_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int racecar_lap_time_mpc_impl_dae_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
