/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) racecar_lap_time_mpc_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {7, 1, 1};
static const casadi_int casadi_s1[3] = {7, 7, 1};
static const casadi_int casadi_s2[3] = {7, 2, 1};
static const casadi_int casadi_s3[3] = {2, 1, 1};

/* racecar_lap_time_mpc_expl_vde_forw:(i0[7],i1[7x7],i2[7x2],i3[2],i4[7])->(o0[7],o1[7x7],o2[7x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38;
  a00=arg[0]? arg[0][1] : 0;
  a01=arg[0]? arg[0][5] : 0;
  a02=cos(a01);
  a03=(a00*a02);
  a04=arg[0]? arg[0][2] : 0;
  a01=sin(a01);
  a05=(a04*a01);
  a03=(a03-a05);
  a05=1.;
  a06=arg[0]? arg[0][4] : 0;
  a07=arg[4]? arg[4][0] : 0;
  a06=(a06*a07);
  a06=(a05-a06);
  a08=(a03/a06);
  if (res[0]!=0) res[0][0]=a08;
  a09=arg[3]? arg[3][1] : 0;
  a10=68.;
  a11=arg[3]? arg[3][0] : 0;
  a12=1.0000000000000000e-03;
  a12=(a00+a12);
  a13=(a04/a12);
  a14=(a11-a13);
  a15=1.2500000000000000e-01;
  a16=arg[0]? arg[0][3] : 0;
  a17=(a15*a16);
  a17=(a17/a12);
  a14=(a14+a17);
  a14=(a10*a14);
  a18=sin(a11);
  a19=(a14*a18);
  a20=1.8000000000000000e+00;
  a21=(a19/a20);
  a09=(a09-a21);
  a21=9.8100000000000007e-02;
  a09=(a09-a21);
  a21=(a16*a04);
  a09=(a09+a21);
  if (res[0]!=0) res[0][1]=a09;
  a11=cos(a11);
  a09=(a14*a11);
  a21=(a09/a20);
  a22=71.;
  a23=(a13+a17);
  a23=(a22*a23);
  a20=(a23/a20);
  a21=(a21-a20);
  a20=(a16*a00);
  a21=(a21-a20);
  if (res[0]!=0) res[0][2]=a21;
  a14=(a15*a14);
  a21=(a14*a11);
  a23=(a15*a23);
  a21=(a21+a23);
  a23=2.9999999999999999e-02;
  a21=(a21/a23);
  if (res[0]!=0) res[0][3]=a21;
  a21=(a00*a01);
  a23=(a04*a02);
  a21=(a21+a23);
  if (res[0]!=0) res[0][4]=a21;
  a03=(a03*a07);
  a03=(a03/a06);
  a21=(a16-a03);
  if (res[0]!=0) res[0][5]=a21;
  a21=-3.3333333333333332e-04;
  a23=1.0718750000000001e-02;
  a20=casadi_sq(a00);
  a20=(a23*a20);
  a24=1.7658000000000004e-01;
  a25=(a24*a00);
  a20=(a20+a25);
  a20=(a21*a20);
  if (res[0]!=0) res[0][6]=a20;
  a20=arg[1]? arg[1][1] : 0;
  a25=(a02*a20);
  a26=arg[1]? arg[1][5] : 0;
  a27=(a01*a26);
  a28=(a00*a27);
  a25=(a25-a28);
  a28=arg[1]? arg[1][2] : 0;
  a29=(a01*a28);
  a26=(a02*a26);
  a30=(a04*a26);
  a29=(a29+a30);
  a25=(a25-a29);
  a29=(a25/a06);
  a08=(a08/a06);
  a30=arg[1]? arg[1][4] : 0;
  a30=(a07*a30);
  a31=(a08*a30);
  a29=(a29+a31);
  if (res[1]!=0) res[1][0]=a29;
  a29=arg[1]? arg[1][3] : 0;
  a31=(a04*a29);
  a32=(a16*a28);
  a31=(a31+a32);
  a32=5.5555555555555558e-01;
  a33=(a15*a29);
  a33=(a33/a12);
  a17=(a17/a12);
  a34=(a17*a20);
  a33=(a33-a34);
  a34=(a28/a12);
  a13=(a13/a12);
  a35=(a13*a20);
  a34=(a34-a35);
  a35=(a33-a34);
  a35=(a10*a35);
  a36=(a18*a35);
  a36=(a32*a36);
  a31=(a31-a36);
  if (res[1]!=0) res[1][1]=a31;
  a31=(a11*a35);
  a31=(a32*a31);
  a34=(a34+a33);
  a34=(a22*a34);
  a33=(a32*a34);
  a31=(a31-a33);
  a33=(a00*a29);
  a36=(a16*a20);
  a33=(a33+a36);
  a31=(a31-a33);
  if (res[1]!=0) res[1][2]=a31;
  a31=3.3333333333333336e+01;
  a35=(a15*a35);
  a35=(a11*a35);
  a34=(a15*a34);
  a35=(a35+a34);
  a35=(a31*a35);
  if (res[1]!=0) res[1][3]=a35;
  a35=(a01*a20);
  a26=(a00*a26);
  a35=(a35+a26);
  a28=(a02*a28);
  a27=(a04*a27);
  a28=(a28-a27);
  a35=(a35+a28);
  if (res[1]!=0) res[1][4]=a35;
  a25=(a07*a25);
  a25=(a25/a06);
  a03=(a03/a06);
  a30=(a03*a30);
  a25=(a25+a30);
  a29=(a29-a25);
  if (res[1]!=0) res[1][5]=a29;
  a29=(a00+a00);
  a25=(a29*a20);
  a25=(a23*a25);
  a20=(a24*a20);
  a25=(a25+a20);
  a25=(a21*a25);
  if (res[1]!=0) res[1][6]=a25;
  a25=arg[1]? arg[1][8] : 0;
  a20=(a02*a25);
  a30=arg[1]? arg[1][12] : 0;
  a35=(a01*a30);
  a28=(a00*a35);
  a20=(a20-a28);
  a28=arg[1]? arg[1][9] : 0;
  a27=(a01*a28);
  a30=(a02*a30);
  a26=(a04*a30);
  a27=(a27+a26);
  a20=(a20-a27);
  a27=(a20/a06);
  a26=arg[1]? arg[1][11] : 0;
  a26=(a07*a26);
  a34=(a08*a26);
  a27=(a27+a34);
  if (res[1]!=0) res[1][7]=a27;
  a27=arg[1]? arg[1][10] : 0;
  a34=(a04*a27);
  a33=(a16*a28);
  a34=(a34+a33);
  a33=(a15*a27);
  a33=(a33/a12);
  a36=(a17*a25);
  a33=(a33-a36);
  a36=(a28/a12);
  a37=(a13*a25);
  a36=(a36-a37);
  a37=(a33-a36);
  a37=(a10*a37);
  a38=(a18*a37);
  a38=(a32*a38);
  a34=(a34-a38);
  if (res[1]!=0) res[1][8]=a34;
  a34=(a11*a37);
  a34=(a32*a34);
  a36=(a36+a33);
  a36=(a22*a36);
  a33=(a32*a36);
  a34=(a34-a33);
  a33=(a00*a27);
  a38=(a16*a25);
  a33=(a33+a38);
  a34=(a34-a33);
  if (res[1]!=0) res[1][9]=a34;
  a37=(a15*a37);
  a37=(a11*a37);
  a36=(a15*a36);
  a37=(a37+a36);
  a37=(a31*a37);
  if (res[1]!=0) res[1][10]=a37;
  a37=(a01*a25);
  a30=(a00*a30);
  a37=(a37+a30);
  a28=(a02*a28);
  a35=(a04*a35);
  a28=(a28-a35);
  a37=(a37+a28);
  if (res[1]!=0) res[1][11]=a37;
  a20=(a07*a20);
  a20=(a20/a06);
  a26=(a03*a26);
  a20=(a20+a26);
  a27=(a27-a20);
  if (res[1]!=0) res[1][12]=a27;
  a27=(a29*a25);
  a27=(a23*a27);
  a25=(a24*a25);
  a27=(a27+a25);
  a27=(a21*a27);
  if (res[1]!=0) res[1][13]=a27;
  a27=arg[1]? arg[1][15] : 0;
  a25=(a02*a27);
  a20=arg[1]? arg[1][19] : 0;
  a26=(a01*a20);
  a37=(a00*a26);
  a25=(a25-a37);
  a37=arg[1]? arg[1][16] : 0;
  a28=(a01*a37);
  a20=(a02*a20);
  a35=(a04*a20);
  a28=(a28+a35);
  a25=(a25-a28);
  a28=(a25/a06);
  a35=arg[1]? arg[1][18] : 0;
  a35=(a07*a35);
  a30=(a08*a35);
  a28=(a28+a30);
  if (res[1]!=0) res[1][14]=a28;
  a28=arg[1]? arg[1][17] : 0;
  a30=(a04*a28);
  a36=(a16*a37);
  a30=(a30+a36);
  a36=(a15*a28);
  a36=(a36/a12);
  a34=(a17*a27);
  a36=(a36-a34);
  a34=(a37/a12);
  a33=(a13*a27);
  a34=(a34-a33);
  a33=(a36-a34);
  a33=(a10*a33);
  a38=(a18*a33);
  a38=(a32*a38);
  a30=(a30-a38);
  if (res[1]!=0) res[1][15]=a30;
  a30=(a11*a33);
  a30=(a32*a30);
  a34=(a34+a36);
  a34=(a22*a34);
  a36=(a32*a34);
  a30=(a30-a36);
  a36=(a00*a28);
  a38=(a16*a27);
  a36=(a36+a38);
  a30=(a30-a36);
  if (res[1]!=0) res[1][16]=a30;
  a33=(a15*a33);
  a33=(a11*a33);
  a34=(a15*a34);
  a33=(a33+a34);
  a33=(a31*a33);
  if (res[1]!=0) res[1][17]=a33;
  a33=(a01*a27);
  a20=(a00*a20);
  a33=(a33+a20);
  a37=(a02*a37);
  a26=(a04*a26);
  a37=(a37-a26);
  a33=(a33+a37);
  if (res[1]!=0) res[1][18]=a33;
  a25=(a07*a25);
  a25=(a25/a06);
  a35=(a03*a35);
  a25=(a25+a35);
  a28=(a28-a25);
  if (res[1]!=0) res[1][19]=a28;
  a28=(a29*a27);
  a28=(a23*a28);
  a27=(a24*a27);
  a28=(a28+a27);
  a28=(a21*a28);
  if (res[1]!=0) res[1][20]=a28;
  a28=arg[1]? arg[1][22] : 0;
  a27=(a02*a28);
  a25=arg[1]? arg[1][26] : 0;
  a35=(a01*a25);
  a33=(a00*a35);
  a27=(a27-a33);
  a33=arg[1]? arg[1][23] : 0;
  a37=(a01*a33);
  a25=(a02*a25);
  a26=(a04*a25);
  a37=(a37+a26);
  a27=(a27-a37);
  a37=(a27/a06);
  a26=arg[1]? arg[1][25] : 0;
  a26=(a07*a26);
  a20=(a08*a26);
  a37=(a37+a20);
  if (res[1]!=0) res[1][21]=a37;
  a37=arg[1]? arg[1][24] : 0;
  a20=(a04*a37);
  a34=(a16*a33);
  a20=(a20+a34);
  a34=(a15*a37);
  a34=(a34/a12);
  a30=(a17*a28);
  a34=(a34-a30);
  a30=(a33/a12);
  a36=(a13*a28);
  a30=(a30-a36);
  a36=(a34-a30);
  a36=(a10*a36);
  a38=(a18*a36);
  a38=(a32*a38);
  a20=(a20-a38);
  if (res[1]!=0) res[1][22]=a20;
  a20=(a11*a36);
  a20=(a32*a20);
  a30=(a30+a34);
  a30=(a22*a30);
  a34=(a32*a30);
  a20=(a20-a34);
  a34=(a00*a37);
  a38=(a16*a28);
  a34=(a34+a38);
  a20=(a20-a34);
  if (res[1]!=0) res[1][23]=a20;
  a36=(a15*a36);
  a36=(a11*a36);
  a30=(a15*a30);
  a36=(a36+a30);
  a36=(a31*a36);
  if (res[1]!=0) res[1][24]=a36;
  a36=(a01*a28);
  a25=(a00*a25);
  a36=(a36+a25);
  a33=(a02*a33);
  a35=(a04*a35);
  a33=(a33-a35);
  a36=(a36+a33);
  if (res[1]!=0) res[1][25]=a36;
  a27=(a07*a27);
  a27=(a27/a06);
  a26=(a03*a26);
  a27=(a27+a26);
  a37=(a37-a27);
  if (res[1]!=0) res[1][26]=a37;
  a37=(a29*a28);
  a37=(a23*a37);
  a28=(a24*a28);
  a37=(a37+a28);
  a37=(a21*a37);
  if (res[1]!=0) res[1][27]=a37;
  a37=arg[1]? arg[1][29] : 0;
  a28=(a02*a37);
  a27=arg[1]? arg[1][33] : 0;
  a26=(a01*a27);
  a36=(a00*a26);
  a28=(a28-a36);
  a36=arg[1]? arg[1][30] : 0;
  a33=(a01*a36);
  a27=(a02*a27);
  a35=(a04*a27);
  a33=(a33+a35);
  a28=(a28-a33);
  a33=(a28/a06);
  a35=arg[1]? arg[1][32] : 0;
  a35=(a07*a35);
  a25=(a08*a35);
  a33=(a33+a25);
  if (res[1]!=0) res[1][28]=a33;
  a33=arg[1]? arg[1][31] : 0;
  a25=(a04*a33);
  a30=(a16*a36);
  a25=(a25+a30);
  a30=(a15*a33);
  a30=(a30/a12);
  a20=(a17*a37);
  a30=(a30-a20);
  a20=(a36/a12);
  a34=(a13*a37);
  a20=(a20-a34);
  a34=(a30-a20);
  a34=(a10*a34);
  a38=(a18*a34);
  a38=(a32*a38);
  a25=(a25-a38);
  if (res[1]!=0) res[1][29]=a25;
  a25=(a11*a34);
  a25=(a32*a25);
  a20=(a20+a30);
  a20=(a22*a20);
  a30=(a32*a20);
  a25=(a25-a30);
  a30=(a00*a33);
  a38=(a16*a37);
  a30=(a30+a38);
  a25=(a25-a30);
  if (res[1]!=0) res[1][30]=a25;
  a34=(a15*a34);
  a34=(a11*a34);
  a20=(a15*a20);
  a34=(a34+a20);
  a34=(a31*a34);
  if (res[1]!=0) res[1][31]=a34;
  a34=(a01*a37);
  a27=(a00*a27);
  a34=(a34+a27);
  a36=(a02*a36);
  a26=(a04*a26);
  a36=(a36-a26);
  a34=(a34+a36);
  if (res[1]!=0) res[1][32]=a34;
  a28=(a07*a28);
  a28=(a28/a06);
  a35=(a03*a35);
  a28=(a28+a35);
  a33=(a33-a28);
  if (res[1]!=0) res[1][33]=a33;
  a33=(a29*a37);
  a33=(a23*a33);
  a37=(a24*a37);
  a33=(a33+a37);
  a33=(a21*a33);
  if (res[1]!=0) res[1][34]=a33;
  a33=arg[1]? arg[1][36] : 0;
  a37=(a02*a33);
  a28=arg[1]? arg[1][40] : 0;
  a35=(a01*a28);
  a34=(a00*a35);
  a37=(a37-a34);
  a34=arg[1]? arg[1][37] : 0;
  a36=(a01*a34);
  a28=(a02*a28);
  a26=(a04*a28);
  a36=(a36+a26);
  a37=(a37-a36);
  a36=(a37/a06);
  a26=arg[1]? arg[1][39] : 0;
  a26=(a07*a26);
  a27=(a08*a26);
  a36=(a36+a27);
  if (res[1]!=0) res[1][35]=a36;
  a36=arg[1]? arg[1][38] : 0;
  a27=(a04*a36);
  a20=(a16*a34);
  a27=(a27+a20);
  a20=(a15*a36);
  a20=(a20/a12);
  a25=(a17*a33);
  a20=(a20-a25);
  a25=(a34/a12);
  a30=(a13*a33);
  a25=(a25-a30);
  a30=(a20-a25);
  a30=(a10*a30);
  a38=(a18*a30);
  a38=(a32*a38);
  a27=(a27-a38);
  if (res[1]!=0) res[1][36]=a27;
  a27=(a11*a30);
  a27=(a32*a27);
  a25=(a25+a20);
  a25=(a22*a25);
  a20=(a32*a25);
  a27=(a27-a20);
  a20=(a00*a36);
  a38=(a16*a33);
  a20=(a20+a38);
  a27=(a27-a20);
  if (res[1]!=0) res[1][37]=a27;
  a30=(a15*a30);
  a30=(a11*a30);
  a25=(a15*a25);
  a30=(a30+a25);
  a30=(a31*a30);
  if (res[1]!=0) res[1][38]=a30;
  a30=(a01*a33);
  a28=(a00*a28);
  a30=(a30+a28);
  a34=(a02*a34);
  a35=(a04*a35);
  a34=(a34-a35);
  a30=(a30+a34);
  if (res[1]!=0) res[1][39]=a30;
  a37=(a07*a37);
  a37=(a37/a06);
  a26=(a03*a26);
  a37=(a37+a26);
  a36=(a36-a37);
  if (res[1]!=0) res[1][40]=a36;
  a36=(a29*a33);
  a36=(a23*a36);
  a33=(a24*a33);
  a36=(a36+a33);
  a36=(a21*a36);
  if (res[1]!=0) res[1][41]=a36;
  a36=arg[1]? arg[1][43] : 0;
  a33=(a02*a36);
  a37=arg[1]? arg[1][47] : 0;
  a26=(a01*a37);
  a30=(a00*a26);
  a33=(a33-a30);
  a30=arg[1]? arg[1][44] : 0;
  a34=(a01*a30);
  a37=(a02*a37);
  a35=(a04*a37);
  a34=(a34+a35);
  a33=(a33-a34);
  a34=(a33/a06);
  a35=arg[1]? arg[1][46] : 0;
  a35=(a07*a35);
  a28=(a08*a35);
  a34=(a34+a28);
  if (res[1]!=0) res[1][42]=a34;
  a34=arg[1]? arg[1][45] : 0;
  a28=(a04*a34);
  a25=(a16*a30);
  a28=(a28+a25);
  a25=(a15*a34);
  a25=(a25/a12);
  a27=(a17*a36);
  a25=(a25-a27);
  a27=(a30/a12);
  a20=(a13*a36);
  a27=(a27-a20);
  a20=(a25-a27);
  a20=(a10*a20);
  a38=(a18*a20);
  a38=(a32*a38);
  a28=(a28-a38);
  if (res[1]!=0) res[1][43]=a28;
  a28=(a11*a20);
  a28=(a32*a28);
  a27=(a27+a25);
  a27=(a22*a27);
  a25=(a32*a27);
  a28=(a28-a25);
  a25=(a00*a34);
  a38=(a16*a36);
  a25=(a25+a38);
  a28=(a28-a25);
  if (res[1]!=0) res[1][44]=a28;
  a20=(a15*a20);
  a20=(a11*a20);
  a27=(a15*a27);
  a20=(a20+a27);
  a20=(a31*a20);
  if (res[1]!=0) res[1][45]=a20;
  a20=(a01*a36);
  a37=(a00*a37);
  a20=(a20+a37);
  a30=(a02*a30);
  a26=(a04*a26);
  a30=(a30-a26);
  a20=(a20+a30);
  if (res[1]!=0) res[1][46]=a20;
  a33=(a07*a33);
  a33=(a33/a06);
  a35=(a03*a35);
  a33=(a33+a35);
  a34=(a34-a33);
  if (res[1]!=0) res[1][47]=a34;
  a34=(a29*a36);
  a34=(a23*a34);
  a36=(a24*a36);
  a34=(a34+a36);
  a34=(a21*a34);
  if (res[1]!=0) res[1][48]=a34;
  a34=arg[2]? arg[2][1] : 0;
  a36=(a02*a34);
  a33=arg[2]? arg[2][5] : 0;
  a35=(a01*a33);
  a20=(a00*a35);
  a36=(a36-a20);
  a20=arg[2]? arg[2][2] : 0;
  a30=(a01*a20);
  a33=(a02*a33);
  a26=(a04*a33);
  a30=(a30+a26);
  a36=(a36-a30);
  a30=(a36/a06);
  a26=arg[2]? arg[2][4] : 0;
  a26=(a07*a26);
  a37=(a08*a26);
  a30=(a30+a37);
  if (res[2]!=0) res[2][0]=a30;
  a30=arg[2]? arg[2][3] : 0;
  a37=(a04*a30);
  a27=(a16*a20);
  a37=(a37+a27);
  a27=(a15*a30);
  a27=(a27/a12);
  a28=(a17*a34);
  a27=(a27-a28);
  a28=(a20/a12);
  a25=(a13*a34);
  a28=(a28-a25);
  a25=(a27-a28);
  a25=(a10*a25);
  a38=(a18*a25);
  a38=(a32*a38);
  a37=(a37-a38);
  a38=(a10*a18);
  a38=(a38+a09);
  a38=(a32*a38);
  a37=(a37-a38);
  if (res[2]!=0) res[2][1]=a37;
  a37=(a10*a11);
  a37=(a37-a19);
  a37=(a32*a37);
  a19=(a11*a25);
  a19=(a32*a19);
  a28=(a28+a27);
  a28=(a22*a28);
  a27=(a32*a28);
  a19=(a19-a27);
  a27=(a00*a30);
  a38=(a16*a34);
  a27=(a27+a38);
  a19=(a19-a27);
  a37=(a37+a19);
  if (res[2]!=0) res[2][2]=a37;
  a37=8.5000000000000000e+00;
  a37=(a37*a11);
  a14=(a14*a18);
  a37=(a37-a14);
  a37=(a31*a37);
  a25=(a15*a25);
  a25=(a11*a25);
  a28=(a15*a28);
  a25=(a25+a28);
  a25=(a31*a25);
  a37=(a37+a25);
  if (res[2]!=0) res[2][3]=a37;
  a37=(a01*a34);
  a33=(a00*a33);
  a37=(a37+a33);
  a20=(a02*a20);
  a35=(a04*a35);
  a20=(a20-a35);
  a37=(a37+a20);
  if (res[2]!=0) res[2][4]=a37;
  a36=(a07*a36);
  a36=(a36/a06);
  a26=(a03*a26);
  a36=(a36+a26);
  a30=(a30-a36);
  if (res[2]!=0) res[2][5]=a30;
  a30=(a29*a34);
  a30=(a23*a30);
  a34=(a24*a34);
  a30=(a30+a34);
  a30=(a21*a30);
  if (res[2]!=0) res[2][6]=a30;
  a30=arg[2]? arg[2][8] : 0;
  a34=(a02*a30);
  a36=arg[2]? arg[2][12] : 0;
  a26=(a01*a36);
  a37=(a00*a26);
  a34=(a34-a37);
  a37=arg[2]? arg[2][9] : 0;
  a20=(a01*a37);
  a36=(a02*a36);
  a35=(a04*a36);
  a20=(a20+a35);
  a34=(a34-a20);
  a20=(a34/a06);
  a35=arg[2]? arg[2][11] : 0;
  a35=(a07*a35);
  a08=(a08*a35);
  a20=(a20+a08);
  if (res[2]!=0) res[2][7]=a20;
  a20=arg[2]? arg[2][10] : 0;
  a08=(a04*a20);
  a33=(a16*a37);
  a08=(a08+a33);
  a33=(a15*a20);
  a33=(a33/a12);
  a17=(a17*a30);
  a33=(a33-a17);
  a12=(a37/a12);
  a13=(a13*a30);
  a12=(a12-a13);
  a13=(a33-a12);
  a10=(a10*a13);
  a18=(a18*a10);
  a18=(a32*a18);
  a08=(a08-a18);
  a05=(a05+a08);
  if (res[2]!=0) res[2][8]=a05;
  a05=(a11*a10);
  a05=(a32*a05);
  a12=(a12+a33);
  a22=(a22*a12);
  a32=(a32*a22);
  a05=(a05-a32);
  a32=(a00*a20);
  a16=(a16*a30);
  a32=(a32+a16);
  a05=(a05-a32);
  if (res[2]!=0) res[2][9]=a05;
  a10=(a15*a10);
  a11=(a11*a10);
  a15=(a15*a22);
  a11=(a11+a15);
  a31=(a31*a11);
  if (res[2]!=0) res[2][10]=a31;
  a01=(a01*a30);
  a00=(a00*a36);
  a01=(a01+a00);
  a02=(a02*a37);
  a04=(a04*a26);
  a02=(a02-a04);
  a01=(a01+a02);
  if (res[2]!=0) res[2][11]=a01;
  a07=(a07*a34);
  a07=(a07/a06);
  a03=(a03*a35);
  a07=(a07+a03);
  a20=(a20-a07);
  if (res[2]!=0) res[2][12]=a20;
  a29=(a29*a30);
  a23=(a23*a29);
  a24=(a24*a30);
  a23=(a23+a24);
  a21=(a21*a23);
  if (res[2]!=0) res[2][13]=a21;
  return 0;
}

CASADI_SYMBOL_EXPORT int racecar_lap_time_mpc_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int racecar_lap_time_mpc_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int racecar_lap_time_mpc_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void racecar_lap_time_mpc_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int racecar_lap_time_mpc_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void racecar_lap_time_mpc_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void racecar_lap_time_mpc_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void racecar_lap_time_mpc_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int racecar_lap_time_mpc_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int racecar_lap_time_mpc_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real racecar_lap_time_mpc_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* racecar_lap_time_mpc_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* racecar_lap_time_mpc_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* racecar_lap_time_mpc_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* racecar_lap_time_mpc_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int racecar_lap_time_mpc_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int racecar_lap_time_mpc_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
